# Generated by Django 4.1.13 on 2023-12-04 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('category', models.CharField(default='Без категории', max_length=32)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('body', models.TextField()),
            ],
        ),
    ]
