FROM nginx:1.25

COPY nginx/prod/prod.conf /etc/nginx/conf.d/default.conf
COPY project/static /srv/www/project/static
COPY project/media /srv/www/project/media
COPY project/logs /srv/www/project/logs
